---
title: "Linear Regression"
author: "Austin Pesina"
date: "9/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Linear Regresson


### Exploratory Analysis

Read csv and prep dataframe

```{r}
df <- read.csv("data/student-mat.csv", sep = ";")
head(df)
summary(df)
any(is.na(df)) # No NA values
str(df)
```



```{r}
library(ggplot2)
library(dplyr)
library(corrgram)
library(corrplot)


num_cols <- sapply(df, is.numeric)
corr_data <- cor(df[,num_cols])
corr_data
corrplot(corr_data, method = "color")

ggplot(df, aes(x = G3)) +
  geom_histogram(bins = 20, alpha = 0.5, fill = "blue")
```




### Split data into train and test set


```{r}
set.seed(101)
library(caret)

# Split data 70/30

train_index <- createDataPartition(df$G3, p = 0.7, list = F)
train <- df[train_index,]
test <- df[-train_index,]

# Run model
lin_model <- lm(G3 ~ ., train)
summary(lin_model)

# Plot out residuals

res <- residuals(lin_model)
res <- as.data.frame(res)
ggplot(res, mapping = aes(res)) + geom_histogram(fill = "blue", alpha = 0.5)
```



### Predictions

```{r}
# Predictions 

g3_preds <- predict(lin_model, test)

# Compare predictions against test set

results <- cbind(g3_preds, test$G3)
colnames(results) <- c("predicted", "actual")
results <- as.data.frame(results)


# Make negative values 0

to_zero <- function(x){
  if (x < 0){
    return(0)
  }else{
    return(x)
  }
}

# Apply zero function

results$predicted <- sapply(results$predicted, to_zero)

# Mean Squared Error

mse <- mean((results$actual - results$predicted)^2)
mse

# Root Means Squared Error

(mse)^0.5

# Sum of Squared Errors

SSE <- sum((results$predicted - results$actual)^2)
SST <- sum((mean(df$G3) - results$actual)^2)
R2 <- 1 - (SSE/SST)
R2
```


