---
title: "Programming Basics"
author: "Austin Pesina"
date: "9/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
temp <- 30

if (temp > 80){
  print("Hot Outside!")
} else if (temp <=80 & temp >= 50){
  print("Nice Outside")
} else if (temp == 45){
  print("Exactly 45 degrees outside!")
}else{
  print("It's less than 50 degrees outside and it's not exactly 45 degrees!")
}
```



```{r}
ham <- 10
cheese <- 12
report <- "blank"

if (ham >= 10 & cheese >= 10){
  report <- "Strong sales of both ham and cheese!"
}else if (ham == 0 & cheese == 0){
  report <- "No sales today!"
}else{
  report <- "We sold something today!"
}
report
```

# Exercise Problems

### 1

Write a script that will print "Even Number" if the variable x is an even number, otherwise print "Not Even":

```{r}
x <- 3
if ((x %% 2) == 0){
  print("Even Number")
}else{print("Not Even")}

```


### 2

Write a script that will print 'Is a Matrix' if the variable x is a matrix, otherwise print "Not a Matrix". Hint: You may want to check out help(is.matrix)

```{r}
x <- matrix()
if (is.matrix(x) == T){
  print("Is a matrix")
}else{print("Not a matrix")}
```

